[build]
  functions = "functions"
  publish = "public"

# [[redirects]]
#   from = "/_static/*"
#   to = "/public/:splat"
#   status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"