[build]
  publish = "_site"
  command = "yarn build"

[context.production]
  environment = { ENVIRONMENT = "production" }

[[headers]]
  for = "/fonts/*"
  [headers.values]
    # cache for 1 year 
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "lighthouse.html"
    
[[redirects]]
  from = "/blog"
  to = "/"

# [[redirects]]
#   from = "/books"
#   to = "/notes/books"

# [[redirects]]
#   from = "/quotes"
#   to = "/notes/quotes"