export default [
  { name: 'Alexander Obenauer', url: 'https://alexanderobenauer.com' },
  { name: 'Amy Hupe', url: 'https://amyhupe.co.uk' },
  { name: 'anhvn', url: 'https://anhvn.com' },
  { name: 'Audacious Fox', url: 'https://audacious.blog' },
  { name: 'Chen Hui Jing', url: 'https://chenhuijing.com' },
  { name: 'Chris Coyier', url: 'https://chriscoyier.net' },
  { name: 'Frank Chimero', url: 'https://frankchimero.com' },
  { name: 'Interconnected', url: 'https://interconnected.org/home' },
  { name: 'James Little', url: 'https://jameslittle.me' },
  { name: 'Jim Nielsen', url: 'https://blog.jim-nielsen.com' },
  { name: 'Jonnie Hallman', url: 'https://destroytoday.com' },
  { name: 'Jules Forrest', url: 'https://julesforrest.com' },
  { name: 'Justin Duke', url: 'https://jmduke.com' },
  { name: 'Kicks Condor', url: 'https://kickscondor.com' },
  { name: 'Maggie Appleton', url: 'https://maggieappleton.com/garden' },
  { name: 'maya.land', url: 'https://maya.land' },
  { name: 'Mu-An Chiou', url: 'https://muan.co' },
  { name: 'Piper Haywood', url: 'https://piperhaywood.com' },
  { name: 'pketh', url: 'https://pketh.org' },
  { name: 'Robin Rendle', url: 'https://robinrendle.com' },
  { name: 'Robin Sloan', url: 'https://robinsloan.com' },
  { name: 'Soroush Khanlou', url: 'http://khanlou.com' },
  { name: 'thesephist', url: 'https://thesephist.com' },
  { name: 'Tom Critchlow', url: 'https://tomcritchlow.com' },
  { name: 'Zach Leatherman', url: 'https://zachleat.com' },
]
