module.exports = [
  { name: 'Alexander Obenauer', url: 'https://alexanderobenauer.com' },
  { name: 'Amy Hupe', url: 'https://amyhupe.co.uk' },
  { name: 'arcana dot computer', url: 'https://www.arcana.computer' },
  { name: 'Audacious Fox', url: 'https://audaciousfox.net' },
  { name: 'Chen Hui Jing', url: 'https://www.chenhuijing.com' },
  { name: 'Frank Chimero', url: 'https://frankchimero.com' },
  { name: 'Interconnected', url: 'https://interconnected.org/home' },
  { name: 'Jim Nielsen', url: 'https://blog.jim-nielsen.com' },
  { name: 'Jules Forrest', url: 'https://julesforrest.com' },
  { name: 'Kicks Condor', url: 'https://www.kickscondor.com' },
  { name: 'Maggie Appleton', url: 'https://maggieappleton.com/garden' },
  { name: 'Mu-An Chiou', url: 'https://muan.co' },
  { name: 'Piper Haywood', url: 'https://piperhaywood.com' },
  { name: 'pketh', url: 'https://pketh.org' },
  { name: 'Robin Rendle', url: 'https://robinrendle.com' },
  { name: 'Robin Sloan', url: 'https://www.robinsloan.com' },
  { name: 'Soroush Khanlou', url: 'http://khanlou.com' },
  { name: 'thesephist', url: 'https://thesephist.com' },
]
